### ISSUE TITLE
Apparent API issue between guard-motion and growl notifications

### ISSUE THREAD

**Issue by philomory** [mordaroso/guard-motion#5]
When I use guard-motion with the growl notifier for guard through the growl gem, I get the following error:

`13:57:04 - ERROR - Error sending notification with growl: undefined method `type=' for #<Growl::Base:0x007f9ca1033f00>`

This appears to be caused by your supplying a :type option Notifier.notify in [runner.rb:47](https://github.com/mordaroso/guard-motion/blob/master/lib/guard/motion/runner.rb#L47); Notifier.notify passes that option  on in the options hash to Notifier::Growl.notify ([notifier.rb:171](https://github.com/guard/guard/blob/master/lib/guard/notifier.rb#L171)), which in turn passes it on to Growl::Base.new ([growl.rb:90](https://github.com/guard/guard/blob/master/lib/guard/notifiers/growl.rb#L90)), which attempts to call self.type= ([growl.rb:148](https://github.com/visionmedia/growl/blob/master/lib/growl/growl.rb#L148)), which doesn't exist.

As far as I can tell there is no need to pass a :type option, as Notifier.notify sets type information based on the :image option ([notifier.rb:165](https://github.com/guard/guard/blob/master/lib/guard/notifier.rb#L165)). According to the [RDoc](http://rubydoc.info/github/guard/guard/master/Guard/Notifier) for Guard::Notifier, the :image option is the intended way to specify a type.

**Comment by mordaroso** [comment]
Fixed by #6
