### ISSUE TITLE
Running tests on a device

### ISSUE THREAD

**Issue by stefanvermaas** [mordaroso/guard-motion#9]
Hi, is it possible to run the spec tests on a device directly? So instead of calling:

``` Ruby
Rake::Task["spec"].invoke
```

call it like this:

``` Ruby
Rake::Task["spec:device"].invoke
```

Is something like this possible? I don't really know where to start, because I don't know where the `App.config` is set.

**Comment by holgersindbaek** [comment]
+1

**Comment by jamonholmgren** [comment]
@stefanvermaas I know this is an incredibly old thread, but you can do this:

``` ruby
gem install when-files-change
when-files-change -- "bundle exec rake spec:device"
```
